C:\pySun\pyS01\django003>manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
January 18, 2018 - 17:12:21
Django version 2.0, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[18/Jan/2018 17:12:35] "GET / HTTP/1.1" 200 16559
[18/Jan/2018 17:12:35] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[18/Jan/2018 17:12:35] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[18/Jan/2018 17:12:35] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[18/Jan/2018 17:12:35] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
Not Found: /favicon.ico
[18/Jan/2018 17:12:35] "GET /favicon.ico HTTP/1.1" 404 1972

### models.py에서 아래 내용 추가 (, on_delete=models.CASCADE,)
### https://docs.djangoproject.com/en/1.11/ref/models/fields/#django.db.models.ForeignKey
author = models.ForeignKey('auth.User', on_delete=models.CASCADE,)

C:\pySun\pyS01\django003>
C:\pySun\pyS01\django003>
C:\pySun\pyS01\django003>manage.py start app blog
Unknown command: 'start'
Type 'manage.py help' for usage.

C:\pySun\pyS01\django003>manage.py startapp blog

C:\pySun\pyS01\django003>manage.py makemigrations blog
Traceback (most recent call last):
  File "C:\pySun\pyS01\django003\manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python36\lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "C:\Python36\lib\site-packages\django\core\management\__init__.py", line 347, in execute
    django.setup()
  File "C:\Python36\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python36\lib\site-packages\django\apps\registry.py", line 112, in populate
    app_config.import_models()
  File "C:\Python36\lib\site-packages\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\pySun\pyS01\django003\blog\models.py", line 5, in <module>
    class Post(models.Model):
  File "C:\pySun\pyS01\django003\blog\models.py", line 6, in Post
    author = models.ForeignKey('auth.User')
TypeError: __init__() missing 1 required positional argument: 'on_delete'

C:\pySun\pyS01\django003>manage.py makemigrations blog
Traceback (most recent call last):
  File "C:\pySun\pyS01\django003\manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python36\lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "C:\Python36\lib\site-packages\django\core\management\__init__.py", line 347, in execute
    django.setup()
  File "C:\Python36\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python36\lib\site-packages\django\apps\registry.py", line 112, in populate
    app_config.import_models()
  File "C:\Python36\lib\site-packages\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\pySun\pyS01\django003\blog\models.py", line 5, in <module>
    class Post(models.Model):
  File "C:\pySun\pyS01\django003\blog\models.py", line 6, in Post
    author = models.ForeignKey('auth.User')
TypeError: __init__() missing 1 required positional argument: 'on_delete'

C:\pySun\pyS01\django003>manage.py makemigrations blog
Migrations for 'blog':
  blog\migrations\0001_initial.py
    - Create model Post
